"""Task 6 - FastAPI model-serving API (+ request logging and Prometheus metrics for Task 8).

Endpoints
  GET  /              -> service info + links
  GET  /health        -> liveness/readiness (model loaded?)
  GET  /model-info    -> model metadata (kind, version, CV metrics, features)
  POST /predict       -> one patient (JSON)  -> prediction + confidence
  POST /predict/batch -> list of patients    -> list of predictions
  GET  /metrics       -> Prometheus metrics (request count/latency + custom model metrics)
  GET  /docs          -> interactive Swagger UI (auto-generated by FastAPI)

Run locally:  uvicorn heart.api:app --host 0.0.0.0 --port 8000
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
import uuid
from contextlib import asynccontextmanager
from typing import Literal, Optional

from fastapi import FastAPI, HTTPException, Request
from prometheus_client import Counter, Histogram
from prometheus_fastapi_instrumentator import Instrumentator
from pydantic import BaseModel, ConfigDict, Field

from heart.predict import load_metadata, load_model, predict_records

# ---------- structured (JSON-lines) logging ----------
logger = logging.getLogger("heart-api")
logger.setLevel(os.getenv("LOG_LEVEL", "INFO"))
_handler = logging.StreamHandler(sys.stdout)
_handler.setFormatter(logging.Formatter("%(message)s"))
logger.addHandler(_handler)
logger.propagate = False


def log_event(**fields):
    fields.setdefault("ts", time.strftime("%Y-%m-%dT%H:%M:%S%z"))
    logger.info(json.dumps(fields, default=str))


# ---------- custom Prometheus metrics ----------
PREDICTIONS = Counter("heart_predictions_total", "Predictions served", ["label"])
PROBABILITY = Histogram("heart_prediction_probability", "Predicted probability of disease",
                        buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
MODEL_ERRORS = Counter("heart_prediction_errors_total", "Failed prediction requests")


# ---------- request / response schemas ----------
class Patient(BaseModel):
    """One patient record. Ranges follow the cleaning rules in config.VALID_RANGES."""
    model_config = ConfigDict(json_schema_extra={"example": {
        "age": 62, "sex": 1, "cp": 4, "trestbps": 150, "chol": 280, "fbs": 0, "restecg": 2,
        "thalach": 115, "exang": 1, "oldpeak": 2.8, "slope": 2, "ca": 2, "thal": 7}})

    age: int = Field(..., ge=18, le=100, description="Age in years")
    sex: Literal[0, 1] = Field(..., description="0 = female, 1 = male")
    cp: Literal[1, 2, 3, 4] = Field(..., description="Chest pain type (4 = asymptomatic)")
    trestbps: float = Field(..., ge=80, le=220, description="Resting blood pressure (mm Hg)")
    chol: float = Field(..., ge=100, le=600, description="Serum cholesterol (mg/dl)")
    fbs: Literal[0, 1] = Field(..., description="Fasting blood sugar > 120 mg/dl")
    restecg: Literal[0, 1, 2] = Field(..., description="Resting ECG result")
    thalach: float = Field(..., ge=60, le=220, description="Max heart rate achieved")
    exang: Literal[0, 1] = Field(..., description="Exercise-induced angina")
    oldpeak: float = Field(..., ge=0, le=7, description="ST depression induced by exercise")
    slope: Literal[1, 2, 3] = Field(..., description="Slope of peak exercise ST segment")
    ca: Optional[int] = Field(None, ge=0, le=3, description="Major vessels coloured (0-3), optional")
    thal: Optional[Literal[3, 6, 7]] = Field(None, description="3 normal, 6 fixed, 7 reversible; optional")


class Prediction(BaseModel):
    prediction: int = Field(..., description="1 = heart disease, 0 = no heart disease")
    label: str
    probability_disease: float
    confidence: float = Field(..., description="Probability of the predicted class")
    model_version: str
    request_id: str


class BatchRequest(BaseModel):
    patients: list[Patient] = Field(..., min_length=1, max_length=100)


# ---------- app ----------
@asynccontextmanager
async def lifespan(_app: FastAPI):
    load_model()                      # fail fast at startup if the model file is missing
    meta = load_metadata()
    log_event(event="startup", model_kind=meta.get("model_kind"),
              model_version=meta.get("model_version"))
    yield
    log_event(event="shutdown")


app = FastAPI(title="Heart Disease Risk API",
              description="MLOps Assignment 1 - Pranay Jain. Predicts heart-disease risk "
                          "from 13 clinical features (UCI Cleveland).",
              version="1.0.0", lifespan=lifespan)

Instrumentator(excluded_handlers=["/metrics"]).instrument(app).expose(app, include_in_schema=False)


@app.middleware("http")
async def access_log(request: Request, call_next):
    request_id = request.headers.get("x-request-id", uuid.uuid4().hex[:12])
    request.state.request_id = request_id
    start = time.perf_counter()
    response = await call_next(request)
    if request.url.path != "/metrics":
        log_event(event="request", request_id=request_id, method=request.method,
                  path=request.url.path, status=response.status_code,
                  latency_ms=round((time.perf_counter() - start) * 1000, 2),
                  client=request.client.host if request.client else None)
    response.headers["x-request-id"] = request_id
    return response


def _model_version() -> str:
    return str(load_metadata().get("model_version", "unknown"))


def _serve(request: Request, patients: list[Patient]) -> list[Prediction]:
    try:
        results = predict_records([p.model_dump() for p in patients])
    except Exception as exc:  # pragma: no cover - defensive
        MODEL_ERRORS.inc()
        log_event(event="prediction_error", request_id=request.state.request_id, error=str(exc))
        raise HTTPException(status_code=500, detail="prediction failed") from exc
    out = []
    for p, r in zip(patients, results):
        PREDICTIONS.labels(label=r["label"]).inc()
        PROBABILITY.observe(r["probability_disease"])
        log_event(event="prediction", request_id=request.state.request_id,
                  prediction=r["prediction"], probability=r["probability_disease"],
                  age=p.age, sex=p.sex, cp=p.cp)
        out.append(Prediction(**r, model_version=_model_version(),
                              request_id=request.state.request_id))
    return out


@app.get("/")
def root():
    return {"service": "heart-disease-risk-api", "docs": "/docs", "health": "/health",
            "predict": "POST /predict", "metrics": "/metrics"}


@app.get("/health")
def health():
    meta = load_metadata()
    return {"status": "ok", "model_loaded": True, "model_kind": meta.get("model_kind"),
            "model_version": meta.get("model_version")}


@app.get("/model-info")
def model_info():
    meta = load_metadata()
    keys = ["model_name", "model_kind", "model_version", "best_params", "cv_metrics",
            "test_metrics", "decision_threshold", "features", "trained_rows", "trained_at_utc"]
    return {k: meta.get(k) for k in keys}


@app.post("/predict", response_model=Prediction)
def predict(patient: Patient, request: Request):
    return _serve(request, [patient])[0]


@app.post("/predict/batch", response_model=list[Prediction])
def predict_batch(batch: BatchRequest, request: Request):
    return _serve(request, batch.patients)
